language: objective-c
osx_image: xcode8.3
xcode_workspace: IosClass.xcworkspace
xcode_scheme: IosClass

script:
  - xcodebuild -scheme IosClass -workspace IosClass.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.2' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)